# Generated by Django 5.2.1 on 2025-06-11 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Kategoriya')),
                ('image', models.ImageField(upload_to='captcha_images/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Captcha rasm',
                'verbose_name_plural': 'Captcha rasmlar',
            },
        ),
        migrations.CreateModel(
            name='CaptchaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('text', 'Matnli savol'), ('image', 'Rasmli savol')], max_length=5, verbose_name='Savol turi')),
                ('question_text', models.CharField(max_length=255, verbose_name='Savol matni')),
                ('correct_answer', models.CharField(max_length=100, verbose_name="To'g'ri javob")),
                ('image_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rasm kategoriyasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Captcha savol',
                'verbose_name_plural': 'Captcha savollar',
            },
        ),
        migrations.CreateModel(
            name='CaptchaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Sessiya kaliti')),
                ('correct_answer', models.CharField(max_length=100, verbose_name="To'g'ri javob")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('expires_at', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tekshirilgan')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='captcha.captchaquestion', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Captcha sessiya',
                'verbose_name_plural': 'Captcha sessiyalar',
            },
        ),
    ]
