# Generated by Django 5.2.1 on 2025-06-09 12:25

import captcha.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=captcha.models.captcha_image_path)),
                ('category', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='captchasession',
            name='answer',
        ),
        migrations.AddField(
            model_name='captchaquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовый вопрос'), ('image', 'Выбор изображений')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='captchaquestion',
            name='target_category',
            field=models.CharField(blank=True, help_text='Категория изображений для выбора (для image типа)', max_length=50),
        ),
        migrations.AddField(
            model_name='captchasession',
            name='image_captcha_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='captchaquestion',
            name='answer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='captchasession',
            name='session_key',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
