# Generated by Django 5.2.1 on 2025-06-13 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captchaimage',
            options={'verbose_name': 'Captcha фото', 'verbose_name_plural': 'Captcha фотографии'},
        ),
        migrations.AlterModelOptions(
            name='captchaquestion',
            options={'verbose_name': 'Captcha вопрос', 'verbose_name_plural': 'Captcha вопросы'},
        ),
        migrations.AlterModelOptions(
            name='captchasession',
            options={'verbose_name': 'Captcha сессия', 'verbose_name_plural': 'Captcha сессии'},
        ),
        migrations.AlterField(
            model_name='captchaimage',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='captchaimage',
            name='image',
            field=models.ImageField(upload_to='captcha_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='captchaimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='captchaquestion',
            name='correct_answer',
            field=models.CharField(max_length=100, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='captchaquestion',
            name='image_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория фото'),
        ),
        migrations.AlterField(
            model_name='captchaquestion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='captchaquestion',
            name='question_text',
            field=models.CharField(max_length=255, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='captchaquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Текстовый вопрос'), ('image', 'Вопрос с фотографией')], max_length=5, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='captchasession',
            name='correct_answer',
            field=models.CharField(max_length=100, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='captchasession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='captchasession',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='captchasession',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
        migrations.AlterField(
            model_name='captchasession',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='captcha.captchaquestion', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='captchasession',
            name='session_key',
            field=models.CharField(max_length=40, unique=True, verbose_name='Ключ сессии'),
        ),
    ]
