# Generated by Django 5.2.1 on 2025-06-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='characteristics',
            field=models.TextField(blank=True, verbose_name='Характеристики'),
        ),
    ]
