# Generated by Django 5.2.1 on 2025-08-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='Meta description'),
        ),
    ]
