# Generated by Django 5.2.1 on 2025-06-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner_images/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=120, verbose_name='Альтернативный текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.banner', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Изображение баннера',
                'verbose_name_plural': 'Изображения баннеров',
                'ordering': ['order', 'id'],
            },
        ),
    ]
