# Generated by Django 5.1.1 on 2025-05-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('link_text', models.CharField(blank=True, default='Подробнее', max_length=100, verbose_name='Текст кнопки')),
                ('image', models.ImageField(blank=True, upload_to='banners/', verbose_name='Изображение')),
                ('background_color', models.CharField(blank=True, help_text='Например: #0099cc или rgba(0,153,204,0.9)', max_length=20, verbose_name='Цвет фона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Рекламный баннер',
                'verbose_name_plural': 'Рекламные баннеры',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
