# Generated by Django 5.2.1 on 2025-06-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='telegram',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
