# Generated by Django 5.2.1 on 2025-08-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_seosettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEOSettings',
        ),
    ]
