# Generated by Django 5.2.1 on 2025-08-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_seosettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='Имя маршрута (url_name) из urls.py. Например: home, product_list, product_detail, service_list, service_detail, contacts', max_length=100, unique=True, verbose_name='URL name страницы')),
                ('title', models.CharField(blank=True, help_text='Заголовок страницы (<title>)', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Описание страницы (meta description)', verbose_name='Meta description')),
                ('canonical', models.URLField(blank=True, help_text='Каноническая ссылка на страницу', verbose_name='Canonical URL')),
            ],
            options={
                'verbose_name': 'SEO-настройка',
                'verbose_name_plural': 'SEO-настройки',
            },
        ),
    ]
