# Generated by Django 5.2.1 on 2025-08-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_seosettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Фоновое фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
