# Generated by Django 5.2.1 on 2025-08-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcharacteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('on_order', 'Под заказ')], default='in_stock', max_length=20, verbose_name='Наличие'),
        ),
    ]
