# Generated by Django 5.2.1 on 2025-08-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_seosettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEOSettings',
        ),
    ]
