# Generated by Django 5.2.1 on 2025-09-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_seosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-имя. Можно указать число (например 1) или слово.', max_length=160, unique=True),
        ),
    ]
