# Generated by Django 5.2.1 on 2025-09-30 13:38

from django.db import migrations, models


def fill_slug_with_id(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    # Быстро и надёжно: одним SQL-запросом
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE products_product
            SET slug = CAST(id AS TEXT)
            WHERE slug IS NULL OR slug = ''
        """)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_slug'),
    ]

    operations = [
        migrations.RunPython(fill_slug_with_id, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=160, unique=True, blank=True),  # unique=True — чтобы не было дублей
        ),
    ]
