# Generated by Django 5.2.1 on 2025-09-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='По умолчанию = id; можно менять.', max_length=160, unique=True),
        ),
    ]
